package Alexandre.Estrella.uv.es

data class Camping(
    val id: String,
    val signatura: String,
    val codEstado: String,
    val estado: String,
    val codCategoria: String,
    val categoria: String,
    val nombre: String,
    val codProvincia: String,
    val provincia: String,
    val codMunicipio: String,
    val municipio: String,
    val cp: String,
    val direccion: String,
    val codTipoVia: String,
    val tipoVia: String,
    val via: String,
    val numero: String,
    val email: String,
    val web: String,
    val codModalidad: String,
    val modalidad: String,
    val numParcelas: String,
    val plazasParcela: String,
    val numBungalows: String,
    val plazasBungalows: String,
    val supLibreAcampada: String,
    val plazasLibreAcampada: String,
    val plazas: String,
    val fechaAlta: String,
    val fechaBaja: String,
    val periodo: String,
    val diasPeriodo: String
)